# Generated by Django 5.1.13 on 2025-11-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_passwordresettoken'),
        ('clients', '0003_client_phone_timeslot_vehicle_washorder_review_and_more'),
    ]

    operations = [
    ]
