# Generated by Django 5.1.13 on 2025-10-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_washer_client_phone_car_washorder'),
        ('washers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorder',
            name='washer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washers.washer'),
        ),
        migrations.DeleteModel(
            name='Washer',
        ),
    ]
