# Generated by Django 5.1.13 on 2025-10-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_washorder_washer_delete_washer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washorder',
            name='car',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='sedan', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.client')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='washorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.vehicle'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
