# Generated by Django 5.1.13 on 2025-10-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_washorder_car_vehicle_washorder_vehicle_and_more'),
        ('washers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('wash_type', models.CharField(choices=[('basic', 'Basic Wash'), ('premium', 'Premium Wash'), ('deluxe', 'Deluxe Wash')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_notified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.vehicle')),
                ('washer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washers.washer')),
            ],
            options={
                'db_table': 'wash_orders',
            },
        ),
    ]
