# Generated by Django 5.1.13 on 2025-11-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_washorder_status_timeslot_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
