# Generated by Django 5.1.13 on 2025-11-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_timeslot_updated_at_alter_timeslot_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
