# Generated by Django 5.1.13 on 2025-10-28 22:50

from django.db import migrations, models


def update_existing_phone_numbers(apps, schema_editor):
    """Update existing washers with null phone numbers to have a default value"""
    Washer = apps.get_model('washers', 'Washer')
    
    # Update existing washers with null phone numbers
    washers_without_phone = Washer.objects.filter(phone__isnull=True)
    for i, washer in enumerate(washers_without_phone):
        # Give them a temporary phone number that follows the pattern
        washer.phone = f"0700000{i:03d}"  # e.g., 0700000001, 0700000002, etc.
        washer.save()


def reverse_phone_update(apps, schema_editor):
    """Reverse the phone number update"""
    pass  # We can't really reverse this meaningfully


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0001_initial'),
    ]

    operations = [
        # First, update existing records with null phone numbers
        migrations.RunPython(update_existing_phone_numbers, reverse_phone_update),
        
        # Then alter the field to be non-nullable
        migrations.AlterField(
            model_name='washer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
